---
name: 'Patchup'
description: 'Keep your fork up to date and apply your patches on top of it'

inputs:
  conflict_reviewers:
    decription: 'Request a review from these users if there is a conflict.'
    required: false
    default: '[]'
  local_branch:
    description: 'Local branch to keep in sync'
    required: false
    default: 'trunk'
  local_path:
    description: 'The path to the local repository on disk. Uses $GITHUB_WORKSPACE if unset.'
    required: false
  github_token:
    description: 'GitHub token used to file PRs. Can be secrets.GITHUB_TOKEN.'
    required: true
  upstream_repo:
    description: 'The upstream repo (same fork network). e.g. someuser/somerepo'
    required: true
  upstream_branch:
    description: 'The upstream branch with changes. Same as local_branch if unset.'
    required: false
  target_tag:
    description: 'Tag that denotes the start of your local patches'
    required: true

outputs:
  pull_request:
    description: 'Pull request number if the run generated one'

runs:
  using: 'node12'
  main: 'dist/index.js'
