---
name: 'Patchup'
description: 'Keep your fork up to date and apply your patches on top of it'

inputs:
  local_path:
    description: 'the path to the local repository on disk. Uses $GITHUB_WORKSPACE if unset.'
    required: false
  local_branch:
    description: 'the local branch to keep in sync'
    required: false
    default: 'master'
  upstream_github:
    description: 'the upstream repo (for filing PRs) in the username:branch format'
    required: true
  upstream_remote:
    description: 'the name of the remote providing the upstream branch'
    required: false
    default: 'upstream'
  upstream_branch:
    required: false
  strategy:
    description: 'how should the branch be kept up to date'
    required: false
    default: 'merge'
  conflict_reviewers:
    decription: 'request a review from these users if there is a conflict'
    required: false
    default: '[]'
  target_tag:
    description: 'the tag that denotes the start of your local patches'
    required: false

outputs:
  pull_request:
    description: 'a pull request number if the run generated one'

runs:
  using: 'node12'
  main: 'dist/index.js'
