name: "unit-tests"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test
